name: monopolis-backup
on:
  schedule:
    - cron: '0 21 * * *' # Every day at 21:00
  workflow_dispatch:

jobs:
  backup:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify backup started
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{'text':'Backing up $GITHUB_REPOSITORY at $GITHUB_SHA'}" $SLACK_DEPLOY_WEBHOOK_URL
        env:
          SLACK_DEPLOY_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}

      - name: Package file name
        run: echo "MONOPOLIS_BACKUP=backup_$(date "+%Y_%m_%d_%H_%M_%S").tar" >> $GITHUB_ENV

      - name: Create local backup
        run: tar -zcvf /tmp/${{ env.MONOPOLIS_BACKUP }} . && mkdir -p ./build/backup && mv /tmp/${{ env.MONOPOLIS_BACKUP }} ./build/backup

      - name: Upload backup
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: monopolis-backup
          AWS_REGION: ${{ secrets.BACKUP_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BACKUP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKUP_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./build/backup
          DEST_DIR: github/${{ env.GITHUB_REPOSITORY }}

      - name: Notify backup finished
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{'text':'Finished backing up $GITHUB_REPOSITORY at $GITHUB_SHA'}" $SLACK_DEPLOY_WEBHOOK_URL
        env:
          SLACK_DEPLOY_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
    runs-on: ubuntu-latest
